// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY_ZL7ubmZbVxUeFGLBDaLz1xVOtcachw',
    appId: '1:921345349849:web:d15b16da0f7b4e701046c8',
    messagingSenderId: '921345349849',
    projectId: 'edukit-85fa4',
    authDomain: 'edukit-85fa4.firebaseapp.com',
    storageBucket: 'edukit-85fa4.firebasestorage.app',
    measurementId: 'G-ESJSKV7TM8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSgrCI_FbJIi2rWZkbMH6MCYtenConDRg',
    appId: '1:921345349849:android:88687bc77c72f29f1046c8',
    messagingSenderId: '921345349849',
    projectId: 'edukit-85fa4',
    storageBucket: 'edukit-85fa4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuGQJjckWTERiPvWbrhMZmoDQ_eDlugbY',
    appId: '1:921345349849:ios:cbe5b5465cdfe10a1046c8',
    messagingSenderId: '921345349849',
    projectId: 'edukit-85fa4',
    storageBucket: 'edukit-85fa4.firebasestorage.app',
    iosBundleId: 'com.example.edukid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuGQJjckWTERiPvWbrhMZmoDQ_eDlugbY',
    appId: '1:921345349849:ios:cbe5b5465cdfe10a1046c8',
    messagingSenderId: '921345349849',
    projectId: 'edukit-85fa4',
    storageBucket: 'edukit-85fa4.firebasestorage.app',
    iosBundleId: 'com.example.edukid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBY_ZL7ubmZbVxUeFGLBDaLz1xVOtcachw',
    appId: '1:921345349849:web:dc34a1dedbde1be41046c8',
    messagingSenderId: '921345349849',
    projectId: 'edukit-85fa4',
    authDomain: 'edukit-85fa4.firebaseapp.com',
    storageBucket: 'edukit-85fa4.firebasestorage.app',
    measurementId: 'G-PNDZ5LGWTF',
  );
}
